version: "2"
services:
  verdaccio:
    image: verdaccio/verdaccio
    expose:
      - 4873
    networks:
      - default
      - reverse-proxy
    volumes:
      - ./conf:/verdaccio/conf
      - ./storage:/verdaccio/storage
      - ./plugins:/verdaccio/plugins
    env_file:
      - .env
    restart: always
networks:
  reverse-proxy:
    external:
      name: reverse-proxy

